# Generated by Django 2.2.8 on 2021-09-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_relations.Category')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_relations.Subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_relations.Subcategory'),
        ),
    ]
