# Generated by Django 2.2.8 on 2021-09-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=100)),
                ('lname', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'tbl_user_registration',
                'managed': True,
            },
        ),
    ]
