# Generated by Django 2.2.8 on 2021-09-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=100)),
                ('pteacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secname', models.CharField(max_length=100)),
                ('pstudent_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Student')),
                ('pteacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Teacher')),
            ],
        ),
    ]
